### ISSUE TITLE
Was plotted der da?

### ISSUE THREAD

**Issue by abresges** [mgilles0/RTOP#1]
Ich habe eine Idee was der plt.hist(pre) Befehl plottet. Ich denke, die blauen Säulen stehen für die erste Zeile und die Orangenen für die zweite Zeile, etc.

In der ersten Zeile (blau) kommt die „4“ nämlich 5 mal vor, deshalb steht der blaue balken rechts auf „5“.

In der zweiten Zeile kommt die 4 nur zweimal vor, deshalb geht der orangene Balken nur bis zur zwei.

**Comment by mgilles0** [comment]
Er gibt also an wie oft der höchste Score eines Items erreicht wurde...

**Comment by abresges** [comment]
Was mich zu dem Schluss führt, dass Du in Deiner Excel-tabelle zeilen und Spalten getauscht hast.. Normalerweise kommen die Eigenschaften die geprüft werden (name, Alter) in die Spaltenköpfe, und die einzelnen Datensätze werden dann Zeilenweise untereinander angefügt.

In Python ist es anscheinend kein Problem, eine Tabelle zu transponieren. Guckst Du hier:

https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.transpose.html

[https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.transpose.html](url)

**Comment by abresges** [comment]
Du musst nur überlegen, in welcher Anordnung SPPS die Daten von Dir erwartet. Ich tippe darauf, dass die Datensätze in den einzelnen Zeilen angeordnet sein sollten
